feat: реализовать работу с пользователями и вещами
gray-alt/java-shareit pull request #2
Opened 2023-06-21 11:26 UTC by gray-alt

2023-06-21 16:23 UTC, EugeneLenkevich requested changes
Привет, Сергей , спасибо за PR

В целом все отлично :)
Отметил пару моментов, ну и на Optional обрати внимание еще раз :)

2023-06-21 16:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +                .itemId(booking.getItem() != null ? booking.getItem().getId() : null)
booking.getItem() != null ? booking.getItem().getId() : null

Optional.ofNullable(booking.getItem).ifPresent(Item::getId).orElse(null)

Можно, кстати, вот так попробовать, то же самое просто синтаксис другой :)

2023-06-21 16:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/exception/AlreadyExistException.java
> +    public synchronized Throwable fillInStackTrace() {
Не уверен что тут нужен synchronized, вряд ли объект исключения будет использоваться в конкурентной среде. Да и то, он же не будет изменяться, зачем его синхронизировать :)

PS не уверен что название метода соответствует тому что он делает, да и, вообще, а нужен ли такой метод, который просто возвращает ссылку на самого себя :)

2023-06-21 16:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Optional<User> optionalUser = userStorage.getUserById(ownerId);
User user = userStorage.getUserById(ownerId).orElseThrow(-> hrow new NotFoundException("Не найден пользователь с id " + ownerId))

Вот так обычно делают, покороче запись :)

2023-06-21 16:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        } else if (itemStorage.isNotItemExist(ownerId, itemId)) {
isNotExist

Давай вот так метод назовем, покороче и грамматичекую ошибку уберем :)

2023-06-21 16:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return optionalItem;
А есть ли смысл проверять optional и возвращать его же,  почему бы не дать конечному коду самому решать что делать в том случае если optional пустой. Ну или раскрывать его и возвращать уже непосредственный объект. А то у нас получается что мы ничего не делаем, но вводим дополнительное ограничение :)

2023-06-21 16:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return Optional.of(UserMapper.toUserDto(optionalUser.orElseThrow()));
Что то тут как то сложно :)
Из optional перекладывается в другой optional. Какого то смыла это не несет, но плодит кучу мелких  объектов которые потом должен будет собирать сборщик мусора. Это дополнительныё расход ресурсов, он должен быть как то обоснован, упрощением кода например, но становится ли тут от этого проще? :) 
Обычно  в Optional оборачивают только результат выполнения метода

2023-06-22 12:08 UTC, gray-alt commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +                .itemId(booking.getItem() != null ? booking.getItem().getId() : null)
Такая конструкция к сожалению не работает. ifPresent ничего не возвращает и после неё невозможно вызвать orElse. (ну или я чего то не могу пока понять).

Испробовал уже все, самое близкое, это получилась вот такое выражение:
Optional.ofNullable(booking.getItem()).orElseGet(() -> new Item(null, null, null, null, null, null)).getId()

Но мне кажется это ещё сложнее для восприятия, чем просто 
booking.getItem() != null ? booking.getItem().getId() : null

2023-06-22 12:38 UTC, gray-alt commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return optionalItem;
По этому поводу у меня есть пара вопросов.
1) Где лучше делать всю проверку результатов, в сервисном слое или уже в контроллере? Я решил делать все проверки в сервисном слое, отсюда и куча проверок тут и выброс исключений. А контроллер только принимает данные из запросов и возвращает результат.
2) У меня всё обёрнуто в Optional, вообще во всех слоях. Может это чересчур и Optional нужно применять только на каком-то одном уровне?

2023-06-22 12:45 UTC, gray-alt commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return Optional.of(UserMapper.toUserDto(optionalUser.orElseThrow()));
Это как раз к вопросу об Optional, а стоит ли на всех слоях оборачивать результат в Optional?
Просто получается, что из сервиса мы получаем Optional с типом User, а обратно нам нужно вернуть Optional с типом UserDto, отсюда куча преобразований. Как тогда лучше сделать, из нижних уровней возвращать сами объекты или пускай уже контроллер возвращает объекты?

2023-06-22 15:54 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +                .itemId(booking.getItem() != null ? booking.getItem().getId() : null)
Ой, да, все верно, перпутал слегка, вот так.

Optional.ofNullable(booking.getItem()).map(Item::getId).orElse(null)

 Ну фишка тут в том что такая цепочка может содержать несколько вызовов, преобразований и пр. Но, в целом, да, это просто синтаксический сахар, надо по месту смотреть как лучше

2023-06-22 15:56 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо 
Как по мне так выразительней стало, как думаешь? :)

2023-06-23 08:29 UTC, gray-alt commented
Да согласен, я сильно что-то переборщил с Optional на всех уровнях ))

2023-06-23 08:43 UTC, gray-alt commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +                .itemId(booking.getItem() != null ? booking.getItem().getId() : null)
Да спасибо, так заработало, переделал все проверки в мапперах на такой способ.

2023-06-23 09:22 UTC, merged

2023-06-23 10:01 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +                .itemId(booking.getItem() != null ? booking.getItem().getId() : null)
Вообще, фишка этой записи вот в чем. Допустим у нас есть еще куча вложенных элементов и нам все надо проверить на null

первый вариант

```
var id = Optional.ofNullable(booking.getItem())
.map(Item::getSubItem)
.map(SubItem::getSubSubItem)
.map(SubSubItem::getId)
.orElse(null)
```
второй

```
Optional.ofNullable(booking.getItem())
.map(Item::getSubItem)
.map(SubItem::getSubSubItem)
.map(SubSubItem::getId)
.ifPresent(id-> {
    log.info("ИД: {}" + id) 
});
```