Add bookings
gray-alt/java-shareit pull request #4
Opened 2023-07-12 09:45 UTC by gray-alt

2023-07-12 15:30 UTC, EugeneLenkevich requested changes
Привет, Сергей, спасибо за PR

В целом все отлично :)
Отметил косметические моменты. Главное - избегатть запросов к БД в цикле, это потом обязательно сильно просадит производительность :)

2023-07-12 15:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingController(@Qualifier("bookingServiceImpl") BookingService bookingService) {
А не проще уж везде использовать @RequiredArgsConstructor ? :)
Вообще,в том случае если у нас есть несколько бинов-реализаций одного интерфейса, то можно одну из них отмнчать аннотацией @Primary и она будет инжектиться по умолчнию

2023-07-12 15:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    BookingOutputDto addBooking(Long bookerId, BookingInputDto bookingInputDto);
А не усложняем ли мы вводя два разных dto на вход и на выход, может проще будет иметь только один BookingDto  для обоих случаев, для этого есть прямо таки необходимость?

2023-07-12 15:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!booking.getBookerOfBookingId().equals(userId) && !booking.getOwnerOfItemId().equals(userId)) {
Можно кстати избежать этой проверки, вот здесь вместо получения сущности по id

bookingRepository.findById(bookingId)

если сделаем запрос в БД с учетом ограничений. То есть, если пользователю не положено видеть данные, то он их вовсе не найдет. Это, кстати, может быть более предпочтительно с точки зрения безопасности, сообщаем меньше лишней информации  :)

2023-07-12 15:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +    Collection<Booking> findAllByItemOwnerIdAndStartLessThanEqualAndEndGreaterThanEqualOrderByStartDesc(Long ownerId,
Чтобы избегать таких длинных методов можно запрос писать в @Query, их потом друг от друга отличать очень сложно :)

2023-07-12 15:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/comment/model/Comment.java
> +@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
А точно в сущности стоит делать поля финальными, мы же хотим изменять сущность в том числе? Смысл в этом есть в случае dto

2023-07-12 15:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                            bookingRepository.findTop1ByItemIdAndItemOwnerIdAndStatusAndStartLessThanOrderByEndDesc(
А тут получается что мы делаем запросы к БД в цикле. А их может оказаться достаточно много. Не уверен что это оптимально, запросы сами по себе дорогая операция. Получится ли тут обойтись меньшим количеством обращений, придумать соответсвующий sql-запрос :)

2023-07-13 06:55 UTC, gray-alt commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingController(@Qualifier("bookingServiceImpl") BookingService bookingService) {
Спасибо, везде привёл к единообразию. :)

2023-07-13 07:11 UTC, gray-alt commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    BookingOutputDto addBooking(Long bookerId, BookingInputDto bookingInputDto);
Спасибо, да действительно оказалось излишним, объединил всё в одну DTO.

2023-07-13 08:10 UTC, gray-alt commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!booking.getBookerOfBookingId().equals(userId) && !booking.getOwnerOfItemId().equals(userId)) {
Спасибо, поправил, сделал запрос к базе сразу со всеми проверками, если что-то есть, то вернётся.

2023-07-13 09:31 UTC, gray-alt commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +    Collection<Booking> findAllByItemOwnerIdAndStartLessThanEqualAndEndGreaterThanEqualOrderByStartDesc(Long ownerId,
Спасибо, переделал слишком длинные методы на @Query

2023-07-13 09:39 UTC, gray-alt commented on src/main/java/ru/practicum/shareit/comment/model/Comment.java
> +@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
По сути сущности нигде не изменяются, в маппере из Dto переходить в объект модели, потом JPA возвращает уже изменённый объект модели (вот тут не знаю, если поля будут не final, то hibernate потом id присвоит через сеттер или создать новый объект и вернёт уже его, надо проверить), ну и далее мы объект снова маппим в dto.  И на каком то из вебинаров ещё в самом начале обучения слышал, что желательно избегать не final полей. После этого у меня во всех сущностях поля final и все изменения полей делаю через создание нового объекта.

2023-07-13 10:56 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/comment/model/Comment.java
> +@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
Возможно это не так очевидно потому что у нас нет никааких сложных расчетов, а только достань/положи объект в базу :)

Однако какая то бизнес-операция может повлечь изменение большого количества сущностей, банально статусы поменять, какие то счетчики и пр. Каждый раз гонять изменения через иммутабельную сущность - лишние накладные расходы и усложенение кода. Далее, у сущности есть свой жизненный цикл, она живет в сессии jpa а не сразу сохраняется в БД, плюс она может быть закэширована и тд и тп. В общем там под капотом может быть еще много всякого.

И если смотреть с архитектурной точки зрения, то место применения Dto - это все же границы слоя, передача данных между слоями или сервисами.

2023-07-13 14:52 UTC, gray-alt commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                            bookingRepository.findTop1ByItemIdAndItemOwnerIdAndStatusAndStartLessThanOrderByEndDesc(
Вроде получилось, но только 2-мя. Первый получает все вещи с последним и следующим бронированием, а второй получает все комментарии тех вещей, которые вернулись в первом запросе. Но запрос получился большой и не сразу можно понять, что он вообще делает :)
И плюс из-за этого пришлось делать ещё один репозиторий, чтобы корректно JPA возвращал объект вещи с бронированиями. В теории есть пример JPQL запроса, с созданием другого объекта, отличного от того, что имплементируется с JpaRepository, но запрос сложный и мне пришлось его писать на нативном SQL.

2023-07-13 14:53 UTC, gray-alt commented on src/main/java/ru/practicum/shareit/comment/model/Comment.java
> +@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
Да действительно есть места, где излишне создаётся ещё одни объект, на основании другого, это когда идёт update вещи или пользователя. Оставил final только в Dto-шках.

2023-07-13 16:58 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо

Ох ну и запросы получились :)

2023-07-14 03:25 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                            bookingRepository.findTop1ByItemIdAndItemOwnerIdAndStatusAndStartLessThanOrderByEndDesc(
Двумя так двумя, это тоже нормально, главное не 20 :)

2023-07-14 06:17 UTC, merged