Add docker
gray-alt/java-shareit pull request #7
Opened 2023-08-09 16:28 UTC by gray-alt

2023-08-10 03:25 UTC, EugeneLenkevich requested changes
Привет, Сергей, спасибо за PR

В целом все отлично :)

В сервере осталась аннотация от валидации давай ее почикаем 

![image](https://github.com/gray-alt/java-shareit/assets/109306643/87b919c2-357d-49aa-81fa-c3a50f02f5f1)

По ТЗ просят убрать всю валидацию из контроллеров модуля server

 С одной стороны кажется немного странным такое требование, но в этом есть своя логика: не дублировать проверки ибо, в будущем, проверки придется править в разных местах и рано или поздно это приведет к рассинхронизации реализаций и появлению множества багов, как следствие. А в микросервисах починка багов - это то еще приключение :)

PS
Иногда вообще как делают. Микросервис разбивают на два модуля: реализация и контракты (все dto и пр интерфейсы). Другой микросервис (в нашем случае это gateway), который хочет обратится к нашему сервису, импортирует наши контракты и с помощью них и строит запросы. Так обеспечивается соответствие API.
В контракты так же может быть помещен и web-клиент со всем настройками, соответственно, импортируем контракты, инжектим бин клиента, вызываем методы клиента, все остальное от нас сокрыто, не надо возится с настройками и API, в теории, всегда у нас соответствует :)

2023-08-10 03:25 UTC, EugeneLenkevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +                        .uriTemplateHandler(new DefaultUriBuilderFactory(serverUrl + API_PREFIX))
Вот тут есть моментик, который можно улучшить :)
 
В самом клиенте происходит создание и настройка web-клинента. С архитектурной точки зрения это не очень хорошо, клиент занимается своей настройкой, это не его обязаность. Настройку лучше вынести вовне. Можно сделать конфигурацию для бина web-clients и далее он, настроенный, будет инжектится как и остальные бины.

Единственное, аннотацию @Service надо убрать, вообще, это алтернативный способ объявления бинов: мы можем на класс повесить аннотацию или создать такую вот конфигурацию если требуется провести какую то настройку при создании 

Пример вот, только подправь под свою реализацию

![image](https://user-images.githubusercontent.com/94845100/193436606-1894b4f9-aa6d-4359-adec-0791cef7a4e6.png)


Таким образом мы можем иметь разные настройки клиентов для разных сред: допустим на продакшн-сервере с TLS, сертификатами и пр, на тестововм стенде простое соединение, а для локального запуска мы можем, например, вообще создать заглушку, которая будет возвращать статический текст :)


https://www.baeldung.com/spring-profiles

2023-08-11 07:24 UTC, gray-alt commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +                        .uriTemplateHandler(new DefaultUriBuilderFactory(serverUrl + API_PREFIX))
Спасибо за подсказки.. 
Получается я мог не создавать в gateway свои собственные dto, а просто добавить в зависимости server и взять dto-шки и другие нужные классы оттуда? И тогда получается нужно было бы просто убрать аннотации валидации из контроллеров в server и перенести их в контроллеры gateway? При этом в dto на server так же бы и остались аннотации проверок такие как NotNull, Future и т.д.? 
Я так попробовал чисто для эксперимента, работает )) Но не знаю правильно ли так было бы, поэтому сюда изменения не пушил..

Конфигурирование веб-клиента добавил, надеюсь правильно. ))

2023-08-11 08:32 UTC, EugeneLenkevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +                        .uriTemplateHandler(new DefaultUriBuilderFactory(serverUrl + API_PREFIX))
Смотри, ТЗ просить просто убрать валидацию с дто сервера

Далее, что касается зависимостей
Не совсем так. Сами микросервисы не должны друг от друга зависеть, тогда у нас может получиться распределенный монолит, изменения в одном микросервисе тянут изменения во всех остальных. И смысл тогда было все это затевать)
Решение тут есть - вынести контракты, то есть dto в отдельный модуль для каждого сервиса

например
gateway-api
server-api

Это именно dto, необходимые для общения с конкретным модулем

Поъяснение, два варианта

Короткий
https://www.vinsguru.com/microservices-architecture-how-to-share-dto-data-transfer-objects/

То есть основная идея - вынести контаракты (dto и, возможно, web-клиенты) в клиентскуий модуль, который будут импортировать другие сервисы (и десериализоватть json используя эти dto). 

Длинный.
Вообще если загуглить "sharing dto between microservices" то можно увидеть огромное количество обсуждений на эту тему
https://stackoverflow.com/questions/1440952/why-are-data-transfer-objects-dtos-an-anti-pattern

Для начала надо понять проблематику  


Предположим у нас есть автосалон. У нас есть модель - автомтобиль. У нас есть несколько отделов которые работают   этой моделью. Вроде все логично, все просто, но не совсем - в каждом отделе модель на самом деле разная (разный набор атрибутов и связанных сущностей): в отделе продаж (цена комплектация м пр), на СТО (уровень масла, пробег и тд), допустим кредитный отдел - залоговая стоимость и доход клиента. 

Допустим у нас монолит.  Тогда у нас в БД будет огромное количество таблиц, которое покрывает требования всех отделов, куча кода и связей. 

Если у нас микросервис, например сделанный из этого монолита. У нас есть одна модель, мы ее выделяем в библиотеку. И теперь, при каждом изменении модели мы будем вынуждены менять все сервисы, иначе, в случае неактуальной модели в одном из них, мы получим несоответствие. Таким образом, мы получаем распределеннывй монолит - все самое плохое и от монолитов и от микросервисов. 

Чтобы этого избежать делают следующее: каждый микросервис имеет свою модель, свой автомобиль со своими полями. Тут нам надо сослаться на DDD (domain driven design)
https://ru.wikipedia.org/wiki/Предметно-ориентированное_проектирование

Причем если, грубо говоря, в двух сервисах dto совпадают, то это не дублирование кода, это просто в данный момент совпадает реализация и их не надо объединять в один модуль. Соотвественно, изменения в одном сервисе касаются только его одного. Так мы делаем наши сервисы независимыми. Если одному сервису надо узнать информацию из модели из другого, он делает http-запрос (или через асинхронные сообщения), получает JSON (или еще какой то формат, не важно), парсит его и берет нужные поля. Чтобы упростить этот парсинг и исключить несоответствия именно в контактах мы импортируем клиентскую библиотеку того сервиса, парсим в его же dto и, далее, перекладываем уже в локальную модель, например.

2023-08-11 08:37 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо 

Вопрос про dto отличный, постарался раскзать про него, все верно что не стал делать связь напрямую :)

2023-08-11 09:01 UTC, gray-alt commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +                        .uriTemplateHandler(new DefaultUriBuilderFactory(serverUrl + API_PREFIX))
Спасибо, стало намного понятнее.. Я так и думал. что это плохая идея, так как сервисы должны быть изолированными друг от друга.. ))

2023-08-11 09:01 UTC, merged